apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . }}
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 443
      targetPort: 8000
      protocol: TCP
      name: https
  selector:
    {{- include "mychart.selectorLabels" . | nindent 4 }}
